auto: true
safe: true
server: true
markdown: kramdown
pygments: true
permalink: /:title.html
#exclude: [shower,themes]

default_theme: ribbon
default_width: 792
default_lang: en
default_body_class: list

author:
    name: Pomin Wu
    # url:  http://example.com/
    company:
        name: 台灣環境資訊協會
        # url:  http://example.com/

fork_url: https://github.com/pm5/jekyller
progress: true
